set( CCDHCPSERVER_VERSION_MAJOR   0   )
set( CCDHCPSERVER_VERSION_MINOR   0   )
set( CCDHCPSERVER_VERSION_PATCH   1   )
set( CCDHCPSERVER_VERSION_BUILD   0   )
set( CCDHCPSERVER_VERSION_CMAKE ${CCDHCPSERVER_VERSION_MAJOR}.${CCDHCPSERVER_VERSION_MINOR}.${CCDHCPSERVER_VERSION_PATCH})

set( PROJECT_DESCRIPTION    "Tftp Server Project." )